version 0.2-3

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -522,63 +522,8 @@ fi
 
 
 
-echo $ac_n "checking for mysql_init in -lmysqlclient""... $ac_c" 1>&6
-echo "configure:527: checking for mysql_init in -lmysqlclient" >&5
-ac_lib_var=`echo mysqlclient'_'mysql_init | sed 'y%./+-%__p_%'`
-if eval "test \"`echo '$''{'ac_cv_lib_$ac_lib_var'+set}'`\" = set"; then
-  echo $ac_n "(cached) $ac_c" 1>&6
-else
-  ac_save_LIBS="$LIBS"
-LIBS="-lmysqlclient  $LIBS"
-cat > conftest.$ac_ext <<EOF
-#line 535 "configure"
-#include "confdefs.h"
-/* Override any gcc2 internal prototype to avoid an error.  */
-/* We use char because int might match the return type of a gcc2
-    builtin and then its argument prototype would still apply.  */
-char mysql_init();
-
-int main() {
-mysql_init()
-; return 0; }
-EOF
-if { (eval echo configure:546: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
-  rm -rf conftest*
-  eval "ac_cv_lib_$ac_lib_var=yes"
-else
-  echo "configure: failed program was:" >&5
-  cat conftest.$ac_ext >&5
-  rm -rf conftest*
-  eval "ac_cv_lib_$ac_lib_var=no"
-fi
-rm -f conftest*
-LIBS="$ac_save_LIBS"
-
-fi
-if eval "test \"`echo '$ac_cv_lib_'$ac_lib_var`\" = yes"; then
-  echo "$ac_t""yes" 1>&6
-    ac_tr_lib=HAVE_LIB`echo mysqlclient | sed -e 's/[^a-zA-Z0-9_]/_/g' \
-    -e 'y/abcdefghijklmnopqrstuvwxyz/ABCDEFGHIJKLMNOPQRSTUVWXYZ/'`
-  cat >> confdefs.h <<EOF
-#define $ac_tr_lib 1
-EOF
-
-  LIBS="-lmysqlclient $LIBS"
-
-else
-  echo "$ac_t""no" 1>&6
-fi
-
-
-for dir in \
-    /usr/include \
-    /usr/include/mysql \
-    /usr/local/include \
-    /usr/local/include/mysql \
-    /opt/include \
-    /opt/include/mysql; do
-    echo $ac_n "checking how to run the C preprocessor""... $ac_c" 1>&6
-echo "configure:582: checking how to run the C preprocessor" >&5
+echo $ac_n "checking how to run the C preprocessor""... $ac_c" 1>&6
+echo "configure:527: checking how to run the C preprocessor" >&5
 # On Suns, sometimes $CPP names a directory.
 if test -n "$CPP" && test -d "$CPP"; then
   CPP=
@@ -593,13 +538,13 @@ else
   # On the NeXT, cc -E runs the code through the compiler's parser,
   # not just through cpp.
   cat > conftest.$ac_ext <<EOF
-#line 597 "configure"
+#line 542 "configure"
 #include "confdefs.h"
 #include <assert.h>
 Syntax Error
 EOF
 ac_try="$ac_cpp conftest.$ac_ext >/dev/null 2>conftest.out"
-{ (eval echo configure:603: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
+{ (eval echo configure:548: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
 ac_err=`grep -v '^ *+' conftest.out | grep -v "^conftest.${ac_ext}\$"`
 if test -z "$ac_err"; then
   :
@@ -610,13 +555,13 @@ else
   rm -rf conftest*
   CPP="${CC-cc} -E -traditional-cpp"
   cat > conftest.$ac_ext <<EOF
-#line 614 "configure"
+#line 559 "configure"
 #include "confdefs.h"
 #include <assert.h>
 Syntax Error
 EOF
 ac_try="$ac_cpp conftest.$ac_ext >/dev/null 2>conftest.out"
-{ (eval echo configure:620: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
+{ (eval echo configure:565: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
 ac_err=`grep -v '^ *+' conftest.out | grep -v "^conftest.${ac_ext}\$"`
 if test -z "$ac_err"; then
   :
@@ -627,13 +572,13 @@ else
   rm -rf conftest*
   CPP="${CC-cc} -nologo -E"
   cat > conftest.$ac_ext <<EOF
-#line 631 "configure"
+#line 576 "configure"
 #include "confdefs.h"
 #include <assert.h>
 Syntax Error
 EOF
 ac_try="$ac_cpp conftest.$ac_ext >/dev/null 2>conftest.out"
-{ (eval echo configure:637: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
+{ (eval echo configure:582: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
 ac_err=`grep -v '^ *+' conftest.out | grep -v "^conftest.${ac_ext}\$"`
 if test -z "$ac_err"; then
   :
@@ -657,19 +602,73 @@ else
 fi
 echo "$ac_t""$CPP" 1>&6
 
-ac_safe=`echo "${dir}/mysql.h" | sed 'y%./+-%__p_%'`
+
+echo $ac_n "checking for mysql_init in -lmysqlclient""... $ac_c" 1>&6
+echo "configure:608: checking for mysql_init in -lmysqlclient" >&5
+ac_lib_var=`echo mysqlclient'_'mysql_init | sed 'y%./+-%__p_%'`
+if eval "test \"`echo '$''{'ac_cv_lib_$ac_lib_var'+set}'`\" = set"; then
+  echo $ac_n "(cached) $ac_c" 1>&6
+else
+  ac_save_LIBS="$LIBS"
+LIBS="-lmysqlclient  $LIBS"
+cat > conftest.$ac_ext <<EOF
+#line 616 "configure"
+#include "confdefs.h"
+/* Override any gcc2 internal prototype to avoid an error.  */
+/* We use char because int might match the return type of a gcc2
+    builtin and then its argument prototype would still apply.  */
+char mysql_init();
+
+int main() {
+mysql_init()
+; return 0; }
+EOF
+if { (eval echo configure:627: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+  rm -rf conftest*
+  eval "ac_cv_lib_$ac_lib_var=yes"
+else
+  echo "configure: failed program was:" >&5
+  cat conftest.$ac_ext >&5
+  rm -rf conftest*
+  eval "ac_cv_lib_$ac_lib_var=no"
+fi
+rm -f conftest*
+LIBS="$ac_save_LIBS"
+
+fi
+if eval "test \"`echo '$ac_cv_lib_'$ac_lib_var`\" = yes"; then
+  echo "$ac_t""yes" 1>&6
+  PKG_LIBS="-lmysqlclient"
+else
+  echo "$ac_t""no" 1>&6
+fi
+
+if test -z "${PKG_LIBS}"; then
+  echo "could not find your MySQL client library"
+  exit 1
+fi
+
+
+for dir in \
+    /usr/include \
+    /usr/include/mysql \
+    /usr/local/include \
+    /usr/local/include/mysql \
+    /opt/include \
+    /opt/include/mysql; do
+    ac_safe=`echo "${dir}/mysql.h" | sed 'y%./+-%__p_%'`
 echo $ac_n "checking for ${dir}/mysql.h""... $ac_c" 1>&6
-echo "configure:663: checking for ${dir}/mysql.h" >&5
+echo "configure:662: checking for ${dir}/mysql.h" >&5
 if eval "test \"`echo '$''{'ac_cv_header_$ac_safe'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 668 "configure"
+#line 667 "configure"
 #include "confdefs.h"
 #include <${dir}/mysql.h>
 EOF
 ac_try="$ac_cpp conftest.$ac_ext >/dev/null 2>conftest.out"
-{ (eval echo configure:673: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
+{ (eval echo configure:672: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
 ac_err=`grep -v '^ *+' conftest.out | grep -v "^conftest.${ac_ext}\$"`
 if test -z "$ac_err"; then
   rm -rf conftest*
@@ -692,6 +691,10 @@ fi
 
     if test $PKG_CPPFLAGS; then break; fi
 done
+if test -z "${PKG_CPPFLAGS}"; then
+  echo "could not find your MySQL header files"
+  exit 1
+fi
 
 
 trap '' 1 2 15
@@ -806,7 +809,7 @@ done
 
 ac_given_srcdir=$srcdir
 
-trap 'rm -fr `echo "src/Makefile" | sed "s/:[^ ]*//g"` conftest*; exit 1' 1 2 15
+trap 'rm -fr `echo "src/Makevars" | sed "s/:[^ ]*//g"` conftest*; exit 1' 1 2 15
 EOF
 cat >> $CONFIG_STATUS <<EOF
 
@@ -839,6 +842,7 @@ s%@oldincludedir@%$oldincludedir%g
 s%@infodir@%$infodir%g
 s%@mandir@%$mandir%g
 s%@CPP@%$CPP%g
+s%@PKG_LIBS@%$PKG_LIBS%g
 s%@PKG_CPPFLAGS@%$PKG_CPPFLAGS%g
 
 CEOF
@@ -881,7 +885,7 @@ EOF
 
 cat >> $CONFIG_STATUS <<EOF
 
-CONFIG_FILES=\${CONFIG_FILES-"src/Makefile"}
+CONFIG_FILES=\${CONFIG_FILES-"src/Makevars"}
 EOF
 cat >> $CONFIG_STATUS <<\EOF
 for ac_file in .. $CONFIG_FILES; do if test "x$ac_file" != x..; then
diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -2,8 +2,15 @@ dnl Borrowed from the RPgSQL package
 dnl Process this file with autoconf to produce a configure script.
 AC_INIT(src/RMySQL.c)
 
+AC_PROG_CPP
+
 dnl Checks for libraries.
-AC_CHECK_LIB(mysqlclient, mysql_init)
+AC_CHECK_LIB(mysqlclient, mysql_init, PKG_LIBS="-lmysqlclient")
+if test -z "${PKG_LIBS}"; then
+  echo "could not find your MySQL client library"
+  exit 1
+fi
+AC_SUBST(PKG_LIBS)
 
 dnl Checks for header files.
 dnl Following courtesy of Kurt Hornik
@@ -17,6 +24,10 @@ for dir in \
     AC_CHECK_HEADER(${dir}/mysql.h, PKG_CPPFLAGS="-I${dir}")
     if test $PKG_CPPFLAGS; then break; fi
 done
+if test -z "${PKG_CPPFLAGS}"; then
+  echo "could not find your MySQL header files"
+  exit 1
+fi
 AC_SUBST(PKG_CPPFLAGS)
 
-AC_OUTPUT(src/Makefile)
+AC_OUTPUT(src/Makevars)
