version 0.5-4

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -609,11 +609,101 @@ fi
 echo "$ac_t""$CPP" 1>&6
 
 
+# Some people have reported not having libz (which we clearly is needed
+# in the INSTALL file).  Oh well.
+#
+echo $ac_n "checking for compress in -lz""... $ac_c" 1>&6
+echo "configure:617: checking for compress in -lz" >&5
+ac_lib_var=`echo z'_'compress | sed 'y%./+-%__p_%'`
+if eval "test \"`echo '$''{'ac_cv_lib_$ac_lib_var'+set}'`\" = set"; then
+  echo $ac_n "(cached) $ac_c" 1>&6
+else
+  ac_save_LIBS="$LIBS"
+LIBS="-lz  $LIBS"
+cat > conftest.$ac_ext <<EOF
+#line 625 "configure"
+#include "confdefs.h"
+/* Override any gcc2 internal prototype to avoid an error.  */
+/* We use char because int might match the return type of a gcc2
+    builtin and then its argument prototype would still apply.  */
+char compress();
+
+int main() {
+compress()
+; return 0; }
+EOF
+if { (eval echo configure:636: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+  rm -rf conftest*
+  eval "ac_cv_lib_$ac_lib_var=yes"
+else
+  echo "configure: failed program was:" >&5
+  cat conftest.$ac_ext >&5
+  rm -rf conftest*
+  eval "ac_cv_lib_$ac_lib_var=no"
+fi
+rm -f conftest*
+LIBS="$ac_save_LIBS"
+
+fi
+if eval "test \"`echo '$ac_cv_lib_'$ac_lib_var`\" = yes"; then
+  echo "$ac_t""yes" 1>&6
+  HAVE_COMPRESS="yes"
+else
+  echo "$ac_t""no" 1>&6
+HAVE_COMPRESS="no"
+fi
+
+
+# Do we have access to GNU's getopt_long (problem on some systems, e.g.,
+# FreeBDS, Mac OS/X, Windows/MinGW)
+#
+echo $ac_n "checking for getopt_long in -lc""... $ac_c" 1>&6
+echo "configure:662: checking for getopt_long in -lc" >&5
+ac_lib_var=`echo c'_'getopt_long | sed 'y%./+-%__p_%'`
+if eval "test \"`echo '$''{'ac_cv_lib_$ac_lib_var'+set}'`\" = set"; then
+  echo $ac_n "(cached) $ac_c" 1>&6
+else
+  ac_save_LIBS="$LIBS"
+LIBS="-lc  $LIBS"
+cat > conftest.$ac_ext <<EOF
+#line 670 "configure"
+#include "confdefs.h"
+/* Override any gcc2 internal prototype to avoid an error.  */
+/* We use char because int might match the return type of a gcc2
+    builtin and then its argument prototype would still apply.  */
+char getopt_long();
+
+int main() {
+getopt_long()
+; return 0; }
+EOF
+if { (eval echo configure:681: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+  rm -rf conftest*
+  eval "ac_cv_lib_$ac_lib_var=yes"
+else
+  echo "configure: failed program was:" >&5
+  cat conftest.$ac_ext >&5
+  rm -rf conftest*
+  eval "ac_cv_lib_$ac_lib_var=no"
+fi
+rm -f conftest*
+LIBS="$ac_save_LIBS"
+
+fi
+if eval "test \"`echo '$ac_cv_lib_'$ac_lib_var`\" = yes"; then
+  echo "$ac_t""yes" 1>&6
+  HAVE_GETOPT_LONG="yes"
+else
+  echo "$ac_t""no" 1>&6
+HAVE_GETOPT_LONG="no"
+fi
+
+
 # can we find MySQL in the system directories? (users may still want/need
 # to use another version/installation)
 #
 echo $ac_n "checking for mysql_init in -lmysqlclient""... $ac_c" 1>&6
-echo "configure:617: checking for mysql_init in -lmysqlclient" >&5
+echo "configure:707: checking for mysql_init in -lmysqlclient" >&5
 ac_lib_var=`echo mysqlclient'_'mysql_init | sed 'y%./+-%__p_%'`
 if eval "test \"`echo '$''{'ac_cv_lib_$ac_lib_var'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
@@ -621,7 +711,7 @@ else
   ac_save_LIBS="$LIBS"
 LIBS="-lmysqlclient  $LIBS"
 cat > conftest.$ac_ext <<EOF
-#line 625 "configure"
+#line 715 "configure"
 #include "confdefs.h"
 /* Override any gcc2 internal prototype to avoid an error.  */
 /* We use char because int might match the return type of a gcc2
@@ -632,7 +722,7 @@ int main() {
 mysql_init()
 ; return 0; }
 EOF
-if { (eval echo configure:636: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+if { (eval echo configure:726: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
   rm -rf conftest*
   eval "ac_cv_lib_$ac_lib_var=yes"
 else
@@ -658,17 +748,17 @@ for ac_hdr in mysql.h
 do
 ac_safe=`echo "$ac_hdr" | sed 'y%./+-%__p_%'`
 echo $ac_n "checking for $ac_hdr""... $ac_c" 1>&6
-echo "configure:662: checking for $ac_hdr" >&5
+echo "configure:752: checking for $ac_hdr" >&5
 if eval "test \"`echo '$''{'ac_cv_header_$ac_safe'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 667 "configure"
+#line 757 "configure"
 #include "confdefs.h"
 #include <$ac_hdr>
 EOF
 ac_try="$ac_cpp conftest.$ac_ext >/dev/null 2>conftest.out"
-{ (eval echo configure:672: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
+{ (eval echo configure:762: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
 ac_err=`grep -v '^ *+' conftest.out | grep -v "^conftest.${ac_ext}\$"`
 if test -z "$ac_err"; then
   rm -rf conftest*
@@ -765,6 +855,10 @@ if test -z "${PKG_CPPFLAGS}" ; then
    fi
 fi
 
+if test "${HAVE_GETOPT_LONG}" = "no" ; then
+   PKG_CPPFLAGS="${PKG_CPPFLAGS} -DHAVE_GETOPT_LONG=0 "
+fi
+
 # if above fails, do a more exhaustive search into potential mysql
 # subdirectories of the system directories.
 if test -z "${HAVE_MYSQL_LIB}" -a -z "${PKG_LIBS}" ; then
@@ -773,7 +867,7 @@ if test -z "${HAVE_MYSQL_LIB}" -a -z "${PKG_LIBS}" ; then
        unset ac_cv_lib_mysqlclient_mysql_init
        candidate="${dir}/mysql"
        echo $ac_n "checking for mysql_init in -lmysqlclient""... $ac_c" 1>&6
-echo "configure:777: checking for mysql_init in -lmysqlclient" >&5
+echo "configure:871: checking for mysql_init in -lmysqlclient" >&5
 ac_lib_var=`echo mysqlclient'_'mysql_init | sed 'y%./+-%__p_%'`
 if eval "test \"`echo '$''{'ac_cv_lib_$ac_lib_var'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
@@ -781,7 +875,7 @@ else
   ac_save_LIBS="$LIBS"
 LIBS="-lmysqlclient -L${candidate} $LIBS"
 cat > conftest.$ac_ext <<EOF
-#line 785 "configure"
+#line 879 "configure"
 #include "confdefs.h"
 /* Override any gcc2 internal prototype to avoid an error.  */
 /* We use char because int might match the return type of a gcc2
@@ -792,7 +886,7 @@ int main() {
 mysql_init()
 ; return 0; }
 EOF
-if { (eval echo configure:796: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+if { (eval echo configure:890: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
   rm -rf conftest*
   eval "ac_cv_lib_$ac_lib_var=yes"
 else
@@ -814,6 +908,7 @@ HAVE_MYSQL_LIB=""
 fi
 
        if test -n "${HAVE_MYSQL_LIB}" ; then
+          echo "             mysqlclient found in -L${HAVE_MYSQL_LIB}"
           PKG_LIBS="-L${HAVE_MYSQL_LIB} -lmysqlclient"
           break
        fi
@@ -827,17 +922,17 @@ if test -z "${HAVE_MYSQL_INC}" -a -z "${PKG_CPPFLAGS}" ; then
        candidate="${dir}/mysql"
        ac_safe=`echo "${candidate}/mysql.h" | sed 'y%./+-%__p_%'`
 echo $ac_n "checking for ${candidate}/mysql.h""... $ac_c" 1>&6
-echo "configure:831: checking for ${candidate}/mysql.h" >&5
+echo "configure:926: checking for ${candidate}/mysql.h" >&5
 if eval "test \"`echo '$''{'ac_cv_header_$ac_safe'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 836 "configure"
+#line 931 "configure"
 #include "confdefs.h"
 #include <${candidate}/mysql.h>
 EOF
 ac_try="$ac_cpp conftest.$ac_ext >/dev/null 2>conftest.out"
-{ (eval echo configure:841: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
+{ (eval echo configure:936: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
 ac_err=`grep -v '^ *+' conftest.out | grep -v "^conftest.${ac_ext}\$"`
 if test -z "$ac_err"; then
   rm -rf conftest*
@@ -866,6 +961,28 @@ fi
        fi
    done
 fi
+
+# don't go any further if don't have libz
+if test "${HAVE_COMPRESS}" = "no" ; then 
+   echo ""
+   echo "Configuration error:"
+   echo '   Could not locate the library "libz" required by MySQL.'
+   echo ""
+   echo "INSTRUCTIONS:" 
+   echo ""
+   echo '   The "libz" library is required by the MySQL client library'
+   echo "   in order to compress/uncompress connections between clients"
+   echo "   and the MySQL engine."
+   echo ""
+   echo '   Make sure you have "libz" installed properly and/or included'
+   echo '   in your $LD_LIBRARY_PATH.  Perhaps it is not in any of the'
+   echo "   standard directories (e.g., /usr/lib/, /usr/local/lib)?"
+   echo ""
+   echo "Aborting the installation of RMySQL."
+   echo ""
+   exit 1
+fi
+
 
 # If we stil haven't set PKG_*, error
 if test "${FOUND_INC}" = "no" -o -z "${PKG_LIBS}" ; then
